apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bankapp-project
  namespace: argocd
spec:
  description: BankApp Project
  sourceRepos:
    - https://github.com/aorko16/Gitops-Bankapp.git
  destinations:
    - namespace: bankapp-ns
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bankapp-project
  source:
    repoURL: https://github.com/aorko16/Gitops-Bankapp.git
    targetRevision: main
    path: K8s   # ⚠️ FIX THIS BASED ON YOUR REPO
  destination:
    server: https://kubernetes.default.svc
    namespace: bankapp-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
